AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
  TargetRubyVersion: 2.6

Style/FormatStringToken:
  Exclude:
    - spec/**/*

Layout/EndOfLine:
  EnforcedStyle: lf

# Trailing white space is meaningful in code examples
Layout/TrailingWhitespace:
  AllowInHeredoc: true

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 120

Metrics/LineLength:
  Max: 120

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Documentation:
  Enabled: false

